# Generated by Django 2.0.4 on 2018-04-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user_type', models.PositiveSmallIntegerField(default=1)),
                ('first_name', models.CharField(default='', max_length=127)),
                ('last_name', models.CharField(default='', max_length=127)),
                ('dob', models.DateField(default=None, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(default=None, max_length=31, null=True)),
                ('contact_no', models.CharField(default=None, max_length=15, null=True)),
                ('image_url', models.URLField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('current_backend', models.CharField(default=None, max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('photo', models.URLField(blank=True, default=None, null=True)),
                ('last_login_store_id', models.IntegerField(default=0, null=True)),
                ('extra_email', models.EmailField(default=None, max_length=254, null=True)),
                ('extra_contact_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('extra_full_name', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('password_expiry_time', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_created_by', to='accounts.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'user_type'), ('contact_no', 'user_type')},
        ),
    ]
