- name: create root project directory
  file: path={{project_root}} owner={{deploy_user}} group={{deploy_user}} mode=0775 state=directory
  sudo: yes
  tags:
    - setup
    - web

- name: Change ownership of codebase to ubuntu
  file: path={{project_root}} state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}} recurse=yes
  sudo: yes
  tags:
    - deploy
    - setup
    - web

- name: deploy code from repository
  action: git accept_hostkey=yes repo={{ repo_url }} dest={{ project_root }}/{{ project_name }} remote={{ repo_remote }} version={{repo_branch}}
  tags:
    - setup
    - deploy
    - web

- name: touch local settings
  file: path={{project_root}}/{{project_name}}/stalwart/settings/local.py state=touch
  sudo: yes
  tags:
    - setup
    - web
    - deploy

- name: Fix for pip bug
  sudo: yes
  shell: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
  tags:
    - setup
    - web

- name: install python dependencies
  sudo: yes
  action: pip requirements={{ project_root }}/{{project_name}}/stalwart/requirements.txt
  tags:
    - setup
    - web

- name: Change ownership of codebase to ubuntu
  file: path={{project_root}} state=directory owner={{deploy_user}} group={{deploy_user}} recurse=yes
  sudo: yes
  tags:
    - deploy
    - setup
    - web
